stages:
  - security

dependencytrack_scan:
  stage: security
  image: alpine:3.19
  only:
    - dev

  script:
    - apk add --no-cache curl wget ca-certificates
    - wget -qO- https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    - syft dir:. -o cyclonedx-json=sbom.json
    - export PROJECT_NAME="${DT_PROJECT_NAME:-$CI_PROJECT_PATH}"
    - export PROJECT_VERSION="${DT_PROJECT_VERSION:-$CI_COMMIT_REF_NAME}"
    - |

      curl -sS -X POST "${DT_URL}/api/v1/bom" \
        -H "X-Api-Key: ${DT_API_KEY}" \
        -H "Content-Type: multipart/form-data" \
        -F "projectName=${PROJECT_NAME}" \
        -F "projectVersion=${PROJECT_VERSION}" \
        -F "autoCreate=true" \
        -F "bom=@sbom.json"
